### ISSUE TITLE
What is the difference between this project and skrafft/react-native-jitsi-meet?

### ISSUE THREAD

**Issue by alexandrtovmach** [sajanthomas01/react-native-jitsi-meet-extended#3]
I saw that you said that referenced repo is not supported anymore, but: "are you sure?" =)

I'm just curious about why this project started, and is there some specific bugfixes or extended functionality? Why just not to create PR to original repo if something small here?

**Comment by sajanthomas01** [comment]
Hi Alexandar, 

What I mentioned is "react-native-jitsi-meet is kind of outdated and no one is releasing any new version of it with new jitsi meet SDK" and that is true because there are PR by devs to upgrade the Jitsi meet SDK but the dev hasn't merged it, seems the last publish to npm was 1 year ago, so there is no point in adding a PR and waiting for it to be merged (at least in my case ), the main thing was I wanted to add some new options to the SDK so that they can also be tweaked, of course, that can be done with the old repo but I was not sure whether putting a PR to that will be merged + added one more mode called activity mode just to invoke jitsi as an activity inside react native app. I'm also working on custom SDK where there will be more options to tweak :), for the extra options you can check the readme file, and also it would be great if you can  help on this to make it a better package :),

**Comment by sajanthomas01** [comment]
> I saw that you said that referenced repo is not supported anymore, but: "are you sure?" =)
> 
> I'm just curious about why this project started, and is there some specific bugfixes or extended functionality? Why just not to create PR to original repo if something small here?

Hi Alexandar,

What I mentioned is "react-native-jitsi-meet is kind of outdated and no one is releasing any new version of it with new jitsi meet SDK" and that is true because there are PR by devs to upgrade the Jitsi meet SDK but the dev hasn't merged it, seems the last publish to npm was 1 year ago, so there is no point in adding a PR and waiting for it to be merged (at least in my case ), the main thing was I wanted to add some new options to the SDK so that they can also be tweaked, of course, that can be done with the old repo but I was not sure whether putting a PR to that will be merged + added one more mode called activity mode just to invoke jitsi as an activity inside react native app. I'm also working on custom SDK where there will be more options to tweak :), for the extra options you can check the readme file, and also it would be great if you can  help on this to make it a better package :),

**Comment by alexandrtovmach** [comment]
Okay, thanks
It's clear for me, but I'd try to keep original repo supported and active. Feel free to join: https://github.com/skrafft/react-native-jitsi-meet/issues/274
